Console login default namespace
UNINETT/kubed pull request #3
Opened 2018-11-01 10:01 UTC by Jondeen

I've added a few functionalities which may be of interest. 

1) Enabling a console version of the token handling. I mostly work in remote consoles, and then it becomes difficult to open a functional js-enabled browser from the shell. -manual-input enables copy-pasting the token request url, and pasting back the authetication token upon redirect. I'm not sure if it is possible to make this more elegant from the server side - if so I'd love to know how to adapt to it.

2) Enabled adding a default namespace to the kube config. Super handy if your work is mostly related to one specific namespace.

Both functionalities store their parameters in kubedconf so it's compatible with a -renew command.

2018-11-01 13:38 UTC, Jondeen commented
I rewrote some hard-coded path changes to make Travis happy (build has been failing for over a year), but double check that these changes are compatible with any downstream systems. There seem to be some inconsistencies in naming convention (`UNINETT` vs `uninett` vs `Uninett`) and I'm not sure which one is correct.

2018-11-01 21:36 UTC, gurvindersingh commented on main.go
> +		fmt.Println("Open a browser and navigate to " + authURL + "?response_type=token&client_id=" + cluster.ClientID + ", then report the return token below.")
Would be good to inform user that here they need to copy token from the url itself. The value is in the request param `access_token`.

2018-11-01 21:41 UTC, gurvindersingh commented on token.go
> -	}
Logic for deletion is that, anyway program will exit and server will be closed or I miss something here.

2018-11-01 21:43 UTC, gurvindersingh commented
Thanks @Jondeen for the PR. Added some small comments. Overall it looks good. Regarding Dataporten response, there is no good way to get the token in user friendly way currently which I am aware of.

Between which institution you work for, as this tool is bit targeted mainly for UH-sector in Norway :)

2018-11-02 17:02 UTC, Jondeen commented
So I fixed the erroneously deleted closure of the http-server instance, and also made a bit more user friendly way of extracting the access_token from the redirect-url.

Travis now fails somehow, though after the push a lot of glitches spun up on the Github/Travis web ui, so I'm wondering if this is issues on the Github/Travis-part and not in the code itself. A manually triggered Travis rebuild would be advised.

2018-11-02 19:24 UTC, Jondeen commented on token.go
> -	}
Seems like Github dropped my previous comment here - but this was wrongfully dropped in my first commit (I think) due to me working on a Go version from before Close() was implemented (1.7). I fixed the drop in the following commit.

2018-11-02 20:25 UTC, gurvindersingh requested changes
Couple of small nits and I am ready to merge.

2018-11-02 20:25 UTC, gurvindersingh commented on main.go
> +		fmt.Print("Redirect-URL: ")
`Redirected-URL:`

2018-11-02 20:25 UTC, gurvindersingh commented on main.go
> +                log.Fatal("Something disastrous happened while getting input from console ", err)
`input from console, please run kubed again"`

2018-11-03 02:47 UTC, gurvindersingh approved these changes

2018-11-03 02:48 UTC, merged